task:
  name: macos_arm64
  trigger_type: manual
  timeout_in: 90m
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  brew_script: brew install cabal-install
  cabal_store_cache:
    folder: ~/.cabal/store
    fingerprint_key: macos_2023_03_11
  deps_script:
    - cabal update
    - cabal build all -fembed_data_files -fserver -flua --dependencies-only
  upload_caches:
    - cabal_store
  install_script: |
    sh macos/make_macos_release.sh
    zip -r macos-release-candidate.zip macos-release-candidate
  artifacts:
    path: macos-release-candidate.zip

task:
  name: linux_arm64
  trigger_type: manual
  timeout_in: 90m
  arm_container:
    image: registry.gitlab.b-data.ch/ghc/ghc4pandoc:9.4.4
    cpu: 4
    memory: 12G
  env:
    CABALOPTS: -f-export-dynamic -fembed_data_files -fserver -flua --enable-executable-static -j4 --ghc-options="-j4 +RTS -A256m -RTS -split-sections -optc-Os -optl=-pthread"
  cabal_store_cache:
    folder: ~/.cabal/store
    fingerprint_key: linux_arm64_2023_03_11
  deps_script:
    - cabal update
    - cabal build --dependencies-only $CABALOPTS pandoc-cli
  upload_caches:
    - cabal_store
  package_script:
    - sh linux/make_artifacts.sh
  release_candidate_artifacts:
    path: ./linux/artifacts/*
