task:
  name: MacOS
  trigger_type: manual
  install_script: brew install cabal-install
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  brew_script: brew install cabal-install
  script:
    - sh macos/make_macos_release.sh
  artifacts:
    path: macos_release_candidate
