task:
  name: MacOS
  trigger_type: manual
  timeout_in: 90m
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  brew_script: brew install cabal-install
  cabal_store_cache:
    folder: ~/.cabal/store
    fingerprint_key: macos_2023_03_11
  deps_script:
    - cabal update
    - cabal build pandoc-cli -fembed_data_files -fserver -flua --dependencies-only
  upload_caches:
    - cabal_store
  install_script: |
    sh macos/make_macos_release.sh
    ls
    zip -r macos-release-candidate.zip macos-release-candidate
  artifacts:
    path: macos-release-candidate.zip
