task:
  name: macos_arm64
  trigger_type: manual
  timeout_in: 90m
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  brew_script: brew install cabal-install
  cabal_store_cache:
    folder: ~/.cabal/store
    fingerprint_key: macos_2023_03_11
  deps_script:
    - cabal update
    - cabal build pandoc-cli -fembed_data_files -fserver -flua --dependencies-only
  upload_caches:
    - cabal_store
  install_script: |
    sh macos/make_macos_release.sh
    ls
    zip -r macos-release-candidate.zip macos-release-candidate
  artifacts:
    path: macos-release-candidate.zip

task:
  name: linux_arm64
  trigger_type: manual
  timeout_in: 90m
  arm_container:
    image: registry.gitlab.b-data.ch/ghc/ghc4pandoc:9.4.4
    cpu: 4
    memory: 12G
  cabal_store_cache:
    folder: ~/.cabal/store
    fingerprint_key: linux_arm64_2023_03_11
  build_script:
    - ARTIFACTS=./linux/artifacts sh linux/make_artifacts.sh
  upload_caches:
    - cabal_store
  artifacts:
    path: ./linux/artifacts/*
