task:
  name: MacOS
  trigger_type: manual
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  brew_script: brew install cabal-install
  script:
    - sh macos/make_macos_release.sh
    - zip -r macos_release_candidate.zip macos_release_candidate
  artifacts:
    path: macos_release_candidate.zip
