flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- skylighting-core-0.12.3
- skylighting-0.12.3
- doctemplates-0.10.0.1
- emojis-0.1.2
- doclayout-0.3.1.1
- lpeg-1.0.3
- hslua-2.2.0
- hslua-aeson-2.2.0
- hslua-classes-2.2.0
- hslua-core-2.2.0
- hslua-marshalling-2.2.0
- hslua-module-doclayout-1.0.3
- hslua-module-path-1.0.2
- hslua-module-system-1.0.2
- hslua-module-text-1.0.2
- hslua-module-version-1.0.2
- hslua-objectorientation-2.2.0
- hslua-packaging-2.2.0
- lua-2.2.0
- lua-arbitrary-1.0.1
- tasty-hslua-1.0.2
- tasty-lua-1.0.2
- pandoc-lua-marshal-0.1.5.1
- aeson-pretty-0.8.9
- unicode-transforms-0.4.0@rev:1
- unicode-data-0.3.0
- commonmark-pandoc-0.2.1.2
- ipynb-0.2
- git: https://github.com/jgm/citeproc.git
  commit: 57975c8b673324140ac0c6adbc1531ff5f6e248a
- git: https://github.com/jgm/commonmark-hs.git
  commit: cc815e013f0d87eef3daef8ad9e376ad807b012b
  subdirs: [commonmark, commonmark-extensions]
- git: https://github.com/jgm/texmath.git
  commit: 506e9433db94246371c1b66f95cf1e3ccab24232
- git: https://github.com/jgm/pandoc-types.git
  commit: feb3a90a17334ab314f63b2de3ec0c7dd59b4be0
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.10
nix:
  packages: [zlib]
