flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- skylighting-core-0.12
- skylighting-0.12
- doctemplates-0.10
- emojis-0.1.2
- doclayout-0.3.1.1
- git: https://github.com/jgm/pandoc-types.git
  commit: f796401eaaab780f83c562e97dbb8c8d4b9974d1
- git: https://github.com/jgm/texmath.git
  commit: c046e6e5a93510f2c37dbc700f82a2c53ed87b5f
- git: https://github.com/jgm/citeproc.git
  commit: 673a7fb643d24a3bb0f60f8f29e189c0ba7ef15b
- git: https://github.com/jgm/commonmark-hs.git
  commit: 7d34a747cd2d8668451909a722eb9ce16d1f4852
  subdirs: [commonmark, commonmark-pandoc]
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-18.10
nix:
  packages: [zlib]


