flags:
  pandoc:
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
- 'pandoc-cli'
- 'pandoc-lua-engine'
- 'pandoc-server'
extra-deps:
- gridtables-0.1.0.0
- hslua-cli-1.2.0
- hslua-list-1.1.0.1
- hslua-module-zip-1.0.0
- jira-wiki-markup-1.5.0
- mime-types-0.1.1.0
- doctemplates-0.11
- texmath-0.12.6
- citeproc-0.8.1
- pandoc-types-1.23
- pandoc-lua-marshal-0.2.0
- commonmark-pandoc-0.2.1.3
- git: https://github.com/jgm/skylighting
  commit: 356be9ee8b3c12f0523a85c00626ee13c155e336
  subdirs: [skylighting-core]

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-20.6
nix:
  packages: [zlib]
