---
name: 📝 Feature Request
description: Propose a new idea or feature
title: "Briefly summarize your request here"
labels: ["enhancement"]
body:
- type: checkboxes
  attributes:
    options:
      - label: I have read the [contributing guide](https://github.com/jgm/CONTRIBUTING.md).
        required: true
      - label: I have searched [the issue tracker](https://github.com/jgm/pandoc/issues) (including closed issues) for similar requests.
        required: true
      - label: I have searched [the pandoc-discuss mailing list](https://groups.google.com/forum/#!forum/pandoc-discuss) for relevant discussions.
        required: true
- type: textarea
  attributes:
    label: Describe your request
    required: true

