name: Nightly

on:
  schedule:
    - cron: '53 6 * * *'

jobs:
  linux:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          ghc --version
          cabal --version
          cabal v2-update
          cabal v2-build --dependencies-only all
    - name: Build
      run: |
          cabal v2-install --install-method=copy --installdir=. all
          strip pandoc
    - name: Install artifact
      run: |
          export ARTIFACTS=nightly-linux/pandoc-nightly-linux-$(date +%Y-%m-%d)
          mkdir -p ${ARTIFACTS}
          cp pandoc ${ARTIFACTS}/pandoc-nightly-${GITHUB_SHA}
    - uses: actions/upload-artifact@master
      with:
        name: nightly-linux
        path: nightly-linux

  windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          ghc --version
          cabal --version
          cabal v2-update
          cabal v2-build --dependencies-only all
    - name: Build artifacts
      shell: cmd
      run: |
          cabal v2-install --install-method=copy --installdir=. all
          for /f %%a in ('powershell -Command "Get-Date -format yyyy-MM-dd"') do set THEDATE=%%a
          set ARTIFACTS=%CD%\nightly-windows\pandoc-nightly-windows-%THEDATE%
          mkdir %ARTIFACTS%
          copy pandoc.exe %ARTIFACTS%\pandoc-nightly-%GITHUB_SHA%.exe
    - uses: actions/upload-artifact@master
      with:
        name: nightly-windows
        path: nightly-windows

  macos:

    runs-on: macOS-10.15

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          ghc --version
          cabal --version
          cabal v2-update
          cabal v2-build --dependencies-only all
    - name: Build
      run: |
          cabal v2-install --install-method=copy --installdir=. all
          strip pandoc
    - name: Install artifact
      run: |
          export ARTIFACTS=nightly-linux/pandoc-nightly-linux-$(date +%Y-%m-%d)
          mkdir -p ${ARTIFACTS}
          cp pandoc ${ARTIFACTS}/pandoc-nightly-${GITHUB_SHA}
    - uses: actions/upload-artifact@master
      with:
        name: nightly-macos
        path: nightly-macos

